### ISSUE TITLE
[bug] transmuter pool isn't being routed through

### ISSUE THREAD

**Issue by doggystylez** [osmosis-labs/sqs#316]
for example:

`https://sqsprod.osmosis.zone/router/custom-direct-quote?tokenIn=4025000000ibc%2F498A0751C798A0D9A389AA3691123DADA57DAA4FE165D5C75894505B876BA6E4&tokenOutDenom=ibc%2FD189335C6E4A68B513C10AB227BF1C1D38C746766278BA3EEB4FB14124F1D858&poolID=1212`

returns:

```
{
  "message": "insufficient balance of token (ibc/D189335C6E4A68B513C10AB227BF1C1D38C746766278BA3EEB4FB14124F1D858), balance (0), amount (4024195000)"
}
```

but it looks like the pool has enough tokens:

```
osmosisd q poolmanager total-pool-liquidity 1212
liquidity:
- amount: "102857295027"
  denom: ibc/D189335C6E4A68B513C10AB227BF1C1D38C746766278BA3EEB4FB14124F1D858
- amount: "547891604973"
  denom: ibc/498A0751C798A0D9A389AA3691123DADA57DAA4FE165D5C75894505B876BA6E4
```
